<a href="https://colab.research.google.com/github/srujan-macharla2003/google-colab/blob/main/array_indexing_And_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Array indexing

In [ ]:
# 1-d array
import numpy as np
var = np.array([1, 2, 3, 4, 5, 6])
print(var[-2])

5


In [ ]:
# 2-d array
var1 = np.array([[9, 8, 7], [4, 5, 6]])
print(var1)
print(var1.ndim)
print(var1[0, 1])

[[9 8 7]
 [4 5 6]]
2
8


In [ ]:
#3-d array
var2 = np.array([[[1, 2], [3, 4]]])
print(var2)
print(var2.ndim)
print(var2[0, 0, 1])


[[[1 2]
  [3 4]]]
3
2


# array slicing

In [ ]:
# 1-d array slicing
# formula = [start:stop:step]
import numpy as np
var = np.array([1,2,3,4,5,6,7])
print(var)
print(var[1:5]) # for values between index 1 to 5, 5 excuded
print(var[1:]) # for values betwenn index 1 to end
print(var[:4]) # for values between start to index 4
print(var[::]) # for values between start to end
print(var[::2]) #for values between start to end with jumping frequency of 2 , 1 will be defulted


[1 2 3 4 5 6 7]
[2 3 4 5]
[2 3 4 5 6 7]
[1 2 3 4]
[1 2 3 4 5 6 7]
[1 3 5 7]


In [ ]:
# 2-d array
# same as 1-d
# formula [set index or row number, start:stop:step]
var1 = np.array([[1, 2, 3, 4 ,5], [9, 8, 7, 6, 5], [11, 12, 13 , 14, 15]])
print(var1.ndim)
print(var1)
print()
print(var1[1, 1:5])

2
[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

[8 7 6 5]


In [ ]:
# 3-d array
# same as 1-d and 2-d
# formula [main index  set number, set index or row number, start:stop:step]
var2 = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(var2.ndim)
print(var2)
print(var2[0,1,1:5])

3
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[ 7  8  9 10]


## Copy And view
Copy is a new array, and the View is just a view of the original array.

Any changes made to the copy will not affect original array.

Any changes made to the view will affect the original array.


In [ ]:
# copy
arr = np.array([1,2,3,4,5,6,7])
print(arr)
copy = arr.copy()
print(copy)
copy[0] = 44
print(copy)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[44  2  3  4  5  6  7]


In [ ]:
# view
arr = np.array([1,2,3,4,5,6,7])
print(arr)
view = arr.view()
print(view)
view[0] = 22
print(view)
print(arr)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[22  2  3  4  5  6  7]
[22  2  3  4  5  6  7]
